* Ben's Top Tip
** Wash Hands
   Regardless of modes of transmission, as we know,
   viruses can survive on surfaces for a while.
   So this means, washing hands, and washing hands correctly,
   can reduce the chances of infections.

** Masks
   The use of masks can help reduce chances that *you*
   can infect other people, if you are sick.

   Often times, people wearing masks keeps adjusting
   them, and this means touching your faces more, which
   means more possibility to be infected.

** Reduce Public Gatherings
   Don't go to large public gatherings. Stay home and stay
   online to keep up with family.
   
   This is a disease where the young can easily spread the
   virus to older people. So just because you feel good does
   not mean you are not contagious. Some reports indicate that
   it's possible that 80% of people are non-symptomatic, meaning
   they get a little sick or not sick at all, but can pass
   the virus on to a lot of people.
   
** Get Connected with Family and Friends Online
   Keep your sanity by connecting with friends and family online.
   Start a project at home. Clean, do taxes, or learn to cook.
   Learn a new language.
   
** Prayer and Meditation
   This is also an excellent to spend your time. Always recommended.

** Check your information sources
   A lot of times, we receive email and facebook messages
   from family and friends that might give us some helpful
   tips and instructions.

   *Verify* the information before believing in them.

   We live in an age of information explosion. Anyone can
   say anything on the Internet. Often people say things
   to either make people feel better or to make people feel
   worried. 
   
*** Checking on snopes.com
*** Be critical of information.
*** Read multiple sources and compare
    Check western and eastern sources:
     For example, check CNN, NBC, AP, WaPo, NYT (Paywall),
     Reuters. But also check news from a different country:
     BBC, Apple News, China Times.
     Also, there are online TV programs and exposes (indenpendent
     reporters).

*** Some ways to tell fake news

    - Machine reading the news
    - A lot of the same repeated information (word-for-word), or
      links to a lot of the same repeated words.
      
      (Example: there was a news about the Mega-Dome in Taiwan used
      as emergency holding place for the sick -- this is debunked as
      fake news)

    - A lot of appeal to emotion
    - Trash talking about other country or groups of people.
      Always be on the look out for blame shifting, finger pointing

    - Appeal to credibility: I have some degree or I have a friend who
      is a doctor. For example: a famous doctor says this.

    - Conspiracy theories
      


